"""OpenAPI spec -> MCP server.

Generation is commodity: FastMCP already does the hard part, so this module is
deliberately thin. The value Tempered adds is everything downstream — proving
the generated server actually rejects what its own schema forbids.

Spec discovery matters more than it looks. Most APIs publish a spec their own
docs never mention, so `find_spec` probes the usual locations before anyone
concludes there is nothing to generate from.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any
from urllib.parse import urljoin
from urllib.request import Request, urlopen

# Where APIs put their spec when the docs do not say.
WELL_KNOWN_PATHS = (
    "/openapi.json",
    "/openapi.yaml",
    "/swagger.json",
    "/v1/openapi.json",
    "/api/openapi.json",
    "/docs/openapi.json",
    "/.well-known/openapi.json",
)

_TEMPLATE = '''"""MCP server generated by Tempered from an OpenAPI spec.

Source: {source}
Do not hand-edit: regenerate, then run `tempered test` against the result.
"""

import json
import os
from pathlib import Path

import httpx2 as httpx
from fastmcp import FastMCP

SPEC = json.loads(Path(__file__).with_name("{spec_file}").read_text(encoding="utf-8"))
BASE_URL = os.environ.get("API_BASE_URL", {base_url!r})

headers = {{}}
if token := os.environ.get("API_TOKEN"):
    headers["Authorization"] = f"Bearer {{token}}"
if extra := os.environ.get("API_HEADERS"):  # e.g. Notion-Version
    headers.update(json.loads(extra))

mcp = FastMCP.from_openapi(
    openapi_spec=SPEC,
    client=httpx.AsyncClient(base_url=BASE_URL, headers=headers, timeout=20.0),
    name={name!r},
)

if __name__ == "__main__":
    mcp.run()
'''


def load_spec(source: str) -> dict[str, Any]:
    """Read an OpenAPI document from a path or URL."""
    if source.startswith(("http://", "https://")):
        text = _fetch(source)
    else:
        text = Path(source).read_text(encoding="utf-8")

    text = text.lstrip()
    if text.startswith("{"):
        return json.loads(text)
    try:
        import yaml  # optional: only needed for YAML specs
    except ImportError as exc:  # pragma: no cover - depends on environment
        raise SystemExit(
            "This spec is YAML. Install pyyaml, or point at the JSON version."
        ) from exc
    return yaml.safe_load(text)


def find_spec(base_url: str) -> str | None:
    """Probe the usual locations for a spec the docs never advertised."""
    for path in WELL_KNOWN_PATHS:
        candidate = urljoin(base_url, path)
        try:
            text = _fetch(candidate).lstrip()
        except Exception:  # noqa: BLE001 - probing, failure is the normal case
            continue
        if text.startswith("{") and '"openapi"' in text[:400] or '"swagger"' in text[:400]:
            return candidate
    return None


def base_url_of(spec: dict[str, Any], source: str = "") -> str:
    """The API's base URL.

    Specs routinely declare a *relative* server url ("/api/v3"). That is legal
    and useless to an HTTP client, so resolve it against wherever the spec was
    fetched from.
    """
    servers = spec.get("servers") or []
    if servers and isinstance(servers[0], dict) and (url := servers[0].get("url")):
        if url.startswith(("http://", "https://")):
            return url
        if source.startswith(("http://", "https://")):
            return urljoin(source, url)
        return url
    # Swagger 2.0 fallback
    if host := spec.get("host"):
        scheme = (spec.get("schemes") or ["https"])[0]
        return f"{scheme}://{host}{spec.get('basePath', '')}"
    return "http://localhost"


READ_ONLY_METHODS = {"get", "head", "options"}


def tool_methods(spec: dict[str, Any]) -> dict[str, str]:
    """Map each generated tool name to the HTTP method behind it.

    MCP carries no signal for whether a tool mutates anything — generated tools
    arrive with no annotations at all — so the only place this is knowable is
    here, at generation time, from the spec. Tempered writes it down beside the
    server so the scanner can refuse to fire adversarial payloads at DELETE.
    """
    methods: dict[str, str] = {}
    for path, operations in (spec.get("paths") or {}).items():
        if not isinstance(operations, dict):
            continue
        for method, operation in operations.items():
            if method.lower() not in {"get", "put", "post", "delete", "patch", "head", "options"}:
                continue
            if isinstance(operation, dict) and (op_id := operation.get("operationId")):
                methods[op_id] = method.lower()
    return methods


def generate(
    source: str, out_dir: Path, base_url: str | None = None, name: str | None = None
) -> Path:
    """Write a runnable MCP server for `source` into `out_dir`."""
    spec = load_spec(source)
    title = spec.get("info", {}).get("title", "api")
    server_name = name or title
    slug = _slug(server_name)

    out_dir.mkdir(parents=True, exist_ok=True)
    spec_file = f"{slug}_openapi.json"
    (out_dir / spec_file).write_text(json.dumps(spec, indent=2), encoding="utf-8")

    server_path = out_dir / f"{slug}_server.py"
    manifest_path(server_path).write_text(
        json.dumps(tool_methods(spec), indent=2), encoding="utf-8"
    )
    server_path.write_text(
        _TEMPLATE.format(
            source=source,
            spec_file=spec_file,
            base_url=base_url or base_url_of(spec, source),
            name=server_name,
        ),
        encoding="utf-8",
    )
    return server_path


def manifest_path(server_path: Path) -> Path:
    """Where the tool -> HTTP method map lives for a generated server."""
    return server_path.with_name(server_path.stem + "_methods.json")


def load_methods(server_path: Path) -> dict[str, str]:
    """Read the method manifest beside a generated server, if there is one."""
    path = manifest_path(server_path)
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _fetch(url: str, timeout: float = 15.0) -> str:
    request = Request(url, headers={"User-Agent": "tempered/0.1"})
    with urlopen(request, timeout=timeout) as response:  # noqa: S310 - explicit http(s) only
        return response.read().decode("utf-8", errors="replace")


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_") or "api"
