"""MCP server generated by Tempered from an OpenAPI spec.

Source: presence/specs/discord.json
Do not hand-edit: regenerate, then run `tempered test` against the result.
"""

import json
import os
from pathlib import Path

import httpx2 as httpx
from fastmcp import FastMCP

SPEC = json.loads(Path(__file__).with_name("discord_openapi.json").read_text(encoding="utf-8"))
BASE_URL = os.environ.get("API_BASE_URL", 'https://discord.com/api')

headers = {}
if token := os.environ.get("API_TOKEN"):
    headers["Authorization"] = f"Bearer {token}"
if extra := os.environ.get("API_HEADERS"):  # e.g. Notion-Version
    headers.update(json.loads(extra))

mcp = FastMCP.from_openapi(
    openapi_spec=SPEC,
    client=httpx.AsyncClient(base_url=BASE_URL, headers=headers, timeout=20.0),
    name='discord',
)

if __name__ == "__main__":
    mcp.run()
